In [9]:
import os 
import pandas as pd

In [10]:
dicionario = {'label':[],'path':[]}

In [14]:
for file in os.listdir('data-train'):
    for i in os.listdir('data-train/'+file):
        dicionario['label'].append(file)
        dicionario['path'].append("data-train/{0}/{1}".format(file,i))

In [8]:
len(lista)

577

In [15]:
df = pd.DataFrame(dicionario)

In [32]:
len(df)

4539

In [26]:
len(df[df['label'] == '448'])

1

In [27]:
os.listdir('data-train')

['-1',
 '0161',
 '0836',
 '0856',
 '0883',
 '100',
 '1001',
 '1018',
 '1019',
 '1035',
 '1039',
 '1059',
 '1077',
 '1078',
 '111',
 '1116',
 '1124',
 '1141',
 '1164',
 '1179',
 '1189',
 '1194',
 '1198',
 '1221',
 '1227',
 '1230',
 '1233',
 '1236',
 '1250',
 '1315',
 '1333',
 '1350',
 '1351',
 '1364',
 '1366',
 '1368',
 '1371',
 '1501',
 '1512',
 '1541',
 '1543',
 '1554',
 '1559',
 '1570',
 '1578',
 '1588',
 '1592',
 '1598',
 '1604',
 '1605',
 '1606',
 '1612',
 '1624',
 '1645',
 '1654',
 '1702',
 '1703',
 '1736',
 '1746',
 '1756',
 '1770',
 '1775',
 '1811',
 '1814',
 '1822',
 '1840',
 '1852',
 '1864',
 '1878',
 '1879',
 '1881',
 '1894',
 '1896',
 '19',
 '1969',
 '1984',
 '1989',
 '1991',
 '1992',
 '1996',
 '1999',
 '2005',
 '2040',
 '2044',
 '2047',
 '2059',
 '2063',
 '2067',
 '2076',
 '2079',
 '2086',
 '2203',
 '2209',
 '2211',
 '2216',
 '2233',
 '2234',
 '2238',
 '2243',
 '2253',
 '2257',
 '2312',
 '2313',
 '232',
 '2327',
 '2350',
 '2351',
 '2352',
 '2354',
 '2385',
 '2386',
 '2388',
 '2390',
 '2392',
 '2393',
 '2395',
 '2396',
 '2401',
 '2402',
 '2412',
 '2419',
 '2420',
 '2426',
 '2448',
 '2458',
 '2469',
 '2470',
 '2471',
 '2488',
 '2489',
 '2495',
 '2496',
 '2500',
 '2501',
 '2529',
 '2532',
 '2535',
 '2537',
 '2542',
 '2544',
 '2556',
 '2562',
 '2564',
 '2578',
 '2579',
 '2580',
 '2581',
 '2582',
 '2583',
 '2585',
 '2604',
 '2607',
 '2608',
 '2609',
 '2610',
 '2611',
 '2612',
 '2622',
 '2624',
 '2625',
 '2628',
 '263',
 '2633',
 '2639',
 '2640',
 '2641',
 '2642',
 '2649',
 '2654',
 '2656',
 '2657',
 '266',
 '2667',
 '2669',
 '2673',
 '2674',
 '2684',
 '2698',
 '2701',
 '2711',
 '2713',
 '2714',
 '2715',
 '2726',
 '2727',
 '2729',
 '2730',
 '2732',
 '2733',
 '2737',
 '2740',
 '2748',
 '2750',
 '2754',
 '2764',
 '2766',
 '2772',
 '2773',
 '2774',
 '2776',
 '2778',
 '2779',
 '2807',
 '2808',
 '2814',
 '2817',
 '2822',
 '2824',
 '2825',
 '2826',
 '2827',
 '2828',
 '2829',
 '2830',
 '2831',
 '2832',
 '2833',
 '2834',
 '2835',
 '2836',
 '2837',
 '2838',
 '2839',
 '2840',
 '2841',
 '2842',
 '2843',
 '2844',
 '2845',
 '2846',
 '2847',
 '2848',
 '2849',
 '2850',
 '2851',
 '2852',
 '2853',
 '2854',
 '2855',
 '2856',
 '2857',
 '2858',
 '2859',
 '2860',
 '2861',
 '2862',
 '2863',
 '2864',
 '2865',
 '2866',
 '2867',
 '2868',
 '2869',
 '2870',
 '2871',
 '2872',
 '2873',
 '2874',
 '2875',
 '2876',
 '2877',
 '2878',
 '2879',
 '2880',
 '2881',
 '2882',
 '2883',
 '2884',
 '2885',
 '2886',
 '2887',
 '2888',
 '2889',
 '2890',
 '2891',
 '2892',
 '2893',
 '2894',
 '2895',
 '2896',
 '2897',
 '2898',
 '2899',
 '2900',
 '2901',
 '2902',
 '2903',
 '2904',
 '2905',
 '2906',
 '2907',
 '2908',
 '2909',
 '2910',
 '2911',
 '2912',
 '2913',
 '2914',
 '2915',
 '2916',
 '2917',
 '2918',
 '2919',
 '2920',
 '2921',
 '2922',
 '2923',
 '2924',
 '2925',
 '2926',
 '2927',
 '2928',
 '2929',
 '2930',
 '2931',
 '2932',
 '2935',
 '2937',
 '2938',
 '2939',
 '2940',
 '2941',
 '2942',
 '2943',
 '2944',
 '2945',
 '2946',
 '2947',
 '2948',
 '2949',
 '2950',
 '2952',
 '2953',
 '2954',
 '2955',
 '2956',
 '2957',
 '2958',
 '2959',
 '2960',
 '2961',
 '2962',
 '2963',
 '2964',
 '2965',
 '2966',
 '2967',
 '2968',
 '2969',
 '2970',
 '2971',
 '2972',
 '2973',
 '2974',
 '2975',
 '2976',
 '2977',
 '2978',
 '2980',
 '2981',
 '2982',
 '2983',
 '2984',
 '2985',
 '2986',
 '2987',
 '2988',
 '2989',
 '2990',
 '2991',
 '2992',
 '2993',
 '2994',
 '2995',
 '2996',
 '2997',
 '2998',
 '2999',
 '3000',
 '3001',
 '3002',
 '3003',
 '3004',
 '3005',
 '3006',
 '3007',
 '3008',
 '3009',
 '3010',
 '3011',
 '3012',
 '3013',
 '3014',
 '3015',
 '3016',
 '3017',
 '3018',
 '3019',
 '3020',
 '3021',
 '3022',
 '3023',
 '3024',
 '3025',
 '3026',
 '3027',
 '3028',
 '3029',
 '3030',
 '3031',
 '3032',
 '3034',
 '3035',
 '3036',
 '3037',
 '3038',
 '3039',
 '3040',
 '3041',
 '3042',
 '3043',
 '3044',
 '3045',
 '3046',
 '3047',
 '3048',
 '3049',
 '3050',
 '3051',
 '3052',
 '3053',
 '3054',
 '3055',
 '3056',
 '3057',
 '3058',
 '3060',
 '3061',
 '3062',
 '3063',
 '3064',
 '3065',
 '3066',
 '3067',
 '3068',
 '3069',
 '3070',
 '3071',
 '3072',
 '3073',
 '3074',
 '3075',
 '3076',
 '3077',
 '3078',
 '3079',
 '3080',
 '3081',
 '3082',
 '3083',
 '3084',
 '3085',
 '3086',
 '3087',
 '3088',
 '3089',
 '3090',
 '3091',
 '3092',
 '3093',
 '3094',
 '3095',
 '3096',
 '3097',
 '3098',
 '3099',
 '3100',
 '3101',
 '3102',
 '3103',
 '3104',
 '3105',
 '3106',
 '3107',
 '3109',
 '3110',
 '3111',
 '3112',
 '3113',
 '3114',
 '3115',
 '3116',
 '3117',
 '3118',
 '3119',
 '3120',
 '3121',
 '3122',
 '3123',
 '3124',
 '3125',
 '3126',
 '3127',
 '3128',
 '3129',
 '3130',
 '3131',
 '3132',
 '3133',
 '3134',
 '3135',
 '3136',
 '3137',
 '3138',
 '3139',
 '3140',
 '3141',
 '3142',
 '3143',
 '3144',
 '3145',
 '3146',
 '3147',
 '3148',
 '3149',
 '3150',
 '3151',
 '3152',
 '3153',
 '3154',
 '3155',
 '3156',
 '3157',
 '3158',
 '3159',
 '3160',
 '3161',
 '3162',
 '3163',
 '3164',
 '3165',
 '3166',
 '3167',
 '3168',
 '3169',
 '3170',
 '3171',
 '3173',
 '3175',
 '3176',
 '3178',
 '3179',
 '3180',
 '3181',
 '3182',
 '3183',
 '3184',
 '3185',
 '3186',
 '3187',
 '3188',
 '3189',
 '3190',
 '3191',
 '3192',
 '3193',
 '3194',
 '3195',
 '3196',
 '3197',
 '3198',
 '3199',
 '3200',
 '3201',
 '3202',
 '3203',
 '3204',
 '3205',
 '3206',
 '3207',
 '3208',
 '3209',
 '3210',
 '3211',
 '3212',
 '3214',
 '3215',
 '3216',
 '3217',
 '3219',
 '3220',
 '3221',
 '3232',
 '3234',
 '3250',
 '3257',
 '3260',
 '3262',
 '3263',
 '3273',
 '3282',
 '3283',
 '3284',
 '3285',
 '3286',
 '3287',
 '3288',
 '3289',
 '3290',
 '3291',
 '3292',
 '3293',
 '3294',
 '3295',
 '3296',
 '3297',
 '3298',
 '3299',
 '3300',
 '3301',
 '3302',
 '3303',
 '3304',
 '3305',
 '3306',
 '3307',
 '3308',
 '3309',
 '3310',
 '3311',
 '3312',
 '3313',
 '3314',
 '3315',
 '3316',
 '3317',
 '3318',
 '3319',
 '3320',
 '3321',
 '3322',
 '3323',
 '3324',
 '3325',
 '3326',
 '3327',
 '3328',
 '3329',
 '3330',
 '3331',
 '3332',
 '3333',
 '3334',
 '3335',
 '3336',
 '3337',
 '3338',
 '3339',
 '3340',
 '3341',
 '3342',
 '3343',
 '3344',
 '3345',
 '3346',
 '3348',
 '3349',
 '3350',
 '3351',
 '3352',
 '3353',
 '3354',
 '3355',
 '3356',
 '3357',
 '3358',
 '3359',
 '3360',
 '3361',
 '3362',
 '3363',
 '3364',
 '3365',
 '3366',
 '3367',
 '3368',
 '3369',
 '3370',
 '3371',
 '3372',
 '3373',
 '3374',
 '3375',
 '3376',
 '3377',
 '3378',
 '3379',
 '3380',
 '3381',
 '3382',
 '3383',
 '3384',
 '3385',
 '3386',
 '3387',
 '3388',
 '3389',
 '3390',
 '3391',
 '3392',
 '3393',
 '3394',
 '3395',
 '3396',
 '3397',
 '3398',
 '3399',
 '3400',
 '3401',
 '3402',
 '3403',
 '3404',
 '3405',
 '3406',
 '3407',
 '3408',
 '3409',
 '3410',
 '3411',
 '3412',
 '3413',
 '3415',
 '3416',
 '3417',
 '3418',
 '3419',
 '3420',
 '3421',
 '3422',
 '3423',
 '3424',
 '3425',
 '3426',
 '3427',
 '3428',
 '3429',
 '3430',
 '3431',
 '3433',
 '3434',
 '3435',
 '3436',
 '3437',
 '3438',
 '3439',
 '3440',
 '3441',
 '3442',
 '3443',
 '3444',
 '3445',
 '3446',
 '3447',
 '3448',
 '3449',
 '3450',
 '3451',
 '3452',
 '3453',
 '3454',
 '3455',
 '3456',
 '3457',
 '3458',
 '3459',
 '3460',
 '3461',
 '3462',
 '3464',
 '3465',
 '3466',
 '3467',
 '3468',
 '3469',
 '3470',
 '3471',
 '3472',
 '3473',
 '3474',
 '3475',
 '3476',
 '3477',
 '3478',
 '3479',
 '3480',
 '3481',
 '3482',
 '3483',
 '3484',
 '3493',
 '3494',
 '3497',
 '3500',
 '3503',
 '3504',
 '3505',
 '3506',
 '3507',
 '3508',
 '3509',
 '3510',
 '3511',
 '3512',
 '3513',
 '3514',
 '3515',
 '3516',
 '3517',
 '3518',
 '3519',
 '3520',
 '3521',
 '3522',
 '3523',
 '3524',
 '3525',
 '3526',
 '3527',
 '3528',
 '3529',
 '3530',
 '3531',
 '3532',
 '3533',
 '3534',
 '3535',
 '3536',
 '3537',
 '3538',
 '3539',
 '3540',
 '3541',
 '3542',
 '3543',
 '3544',
 '3545',
 '3546',
 '3547',
 '3548',
 '3549',
 '3550',
 '3551',
 '3552',
 '3553',
 '3554',
 '3555',
 '3556',
 '3557',
 '3558',
 '3559',
 '3560',
 '3561',
 '3562',
 '3563',
 '3564',
 '3565',
 '3566',
 '3567',
 '3568',
 '3569',
 '3570',
 '3571',
 '3572',
 '3573',
 '3574',
 '3575',
 '3576',
 '3577',
 '3578',
 '3579',
 '3580',
 '3581',
 '3582',
 '3583',
 '3584',
 '3585',
 '3586',
 '3587',
 '3588',
 '3589',
 '3590',
 '3591',
 '3592',
 '3593',
 '3594',
 '3595',
 '3596',
 '3597',
 '3598',
 '3599',
 '3600',
 '3601',
 '3602',
 '3603',
 '3604',
 '3605',
 '3606',
 '3607',
 '3608',
 '3609',
 '3610',
 '3611',
 '3612',
 '3613',
 '3614',
 '3615',
 '3616',
 '3617',
 '3618',
 '3619',
 '3620',
 '3621',
 '3622',
 '3623',
 '3624',
 '3625',
 '3626',
 '3627',
 '3628',
 '3629',
 '3630',
 '3631',
 '3632',
 '3633',
 '3634',
 '3635',
 '3636',
 '3637',
 '3638',
 '3639',
 '3640',
 '3641',
 '3642',
 '3643',
 '3644',
 '3645',
 '3646',
 '3647',
 '3648',
 '3649',
 '3650',
 '3651',
 '3652',
 '3653',
 '3654',
 '3655',
 '3656',
 '3657',
 '3658',
 '3659',
 '3660',
 '3661',
 '3662',
 '3663',
 '3664',
 '3665',
 '3666',
 '3667',
 '3668',
 '3669',
 '3670',
 '3671',
 '3672',
 '3673',
 '3674',
 '3675',
 '3676',
 '3677',
 '3678',
 '3679',
 '3680',
 '3681',
 '3682',
 '3683',
 '3684',
 '3685',
 '3686',
 '3687',
 '3688',
 '3689',
 '3690',
 '3691',
 '3692',
 '3693',
 '3694',
 '3695',
 '3696',
 '3697',
 '3698',
 '3699',
 ...]

In [31]:
df = df.drop_duplicates()

In [34]:
df = df.reset_index()

In [35]:
df.head(25)

    index label                                    path
0       0    -1   data-train/-1/PM-WWA-20050416-037.jpg
1       1    -1   data-train/-1/PM-WWA-20050513-229.jpg
2       2    -1   data-train/-1/PM-WWA-20050513-243.jpg
3       3    -1   data-train/-1/PM-WWA-20050520-134.jpg
4       4    -1   data-train/-1/PM-WWA-20050612-047.jpg
5       5    -1   data-train/-1/PM-WWA-20050620-042.jpg
6       6    -1   data-train/-1/PM-WWA-20050623-066.jpg
7       7    -1   data-train/-1/PM-WWA-20050625-132.jpg
8       8    -1   data-train/-1/PM-WWA-20050625-133.jpg
9       9    -1   data-train/-1/PM-WWA-20050704-012.jpg
10     10    -1  data-train/-1/PM-WWA-20050706-A004.jpg
11     11    -1  data-train/-1/PM-WWA-20050706-A006.jpg
12     12    -1   data-train/-1/PM-WWA-20050707-365.jpg
13     13    -1   data-train/-1/PM-WWA-20050710-073.jpg
14     14    -1   data-train/-1/PM-WWA-20050710-085.jpg
15     15    -1   data-train/-1/PM-WWA-20050710-088.jpg
16     16    -1   data-train/-1/PM-WWA-20050710-115.jpg
17     17    -1   data-train/-1/PM-WWA-20050714-088.jpg
18     18    -1   data-train/-1/PM-WWA-20050716-183.jpg
19     19    -1   data-train/-1/PM-WWA-20050718-126.jpg
20     20    -1   data-train/-1/PM-WWA-20050722-097.jpg
21     21    -1   data-train/-1/PM-WWA-20050723-081.jpg
22     22    -1   data-train/-1/PM-WWA-20050723-109.jpg
23     23    -1   data-train/-1/PM-WWA-20050723-123.jpg
24     24    -1   data-train/-1/PM-WWA-20050723-195.jpg

In [36]:
df.drop('index',axis=1,inplace=True)

In [37]:
df.head()

  label                                   path
0    -1  data-train/-1/PM-WWA-20050416-037.jpg
1    -1  data-train/-1/PM-WWA-20050513-229.jpg
2    -1  data-train/-1/PM-WWA-20050513-243.jpg
3    -1  data-train/-1/PM-WWA-20050520-134.jpg
4    -1  data-train/-1/PM-WWA-20050612-047.jpg

In [38]:
df.to_csv("dataset_train.csv",index=False)

In [39]:
df.head()

  label                                   path
0    -1  data-train/-1/PM-WWA-20050416-037.jpg
1    -1  data-train/-1/PM-WWA-20050513-229.jpg
2    -1  data-train/-1/PM-WWA-20050513-243.jpg
3    -1  data-train/-1/PM-WWA-20050520-134.jpg
4    -1  data-train/-1/PM-WWA-20050612-047.jpg

In [40]:
df.label.value_counts()

-1      577
2352     37
1543     24
2529     23
2628     22
       ...
3763      1
3560      1
5691      1
3437      1
5212      1
Name: label, Length: 2235, dtype: int64

In [60]:
df[(df['label'] == '2352') | (df['label'] == '1543') | (df['label'] == '2529') | (df['label'] == '2628') | (df['label'] == '1333') | (df['label'] == '2556') | (df['label'] == '1746') | (df['label'] == '2907') | (df['label'] == '2579') | (df['label'] == '3101')]

     label                                        path
674   1333     data-train/1333/PM-WWA-20050620-050.jpg
675   1333     data-train/1333/PM-WWA-20050620-153.jpg
676   1333     data-train/1333/PM-WWA-20070526-232.jpg
677   1333     data-train/1333/PM-WWA-20070617-087.jpg
678   1333     data-train/1333/PM-WWA-20070620-023.jpg
...    ...                                         ...
2015  3101    data-train/3101/PM-WWA-20060613-A072.jpg
2016  3101    data-train/3101/PM-WWA-20060613-A090.jpg
2017  3101     data-train/3101/PM-WWA-20060618-003.jpg
2018  3101  data-train/3101/PM-WWA-20060618-051-01.tif
2019  3101     data-train/3101/PM-WWA-20060618-059.jpg

[207 rows x 2 columns]

In [59]:
df[(df['label'] == '2352') | (df['label'] == '1543')]

    label                                      path
730  1543   data-train/1543/PM-WWA-20050612-045.jpg
731  1543   data-train/1543/PM-WWA-20050831-075.jpg
732  1543   data-train/1543/PM-WWA-20050907-003.jpg
733  1543   data-train/1543/PM-WWA-20060530-126.jpg
734  1543  data-train/1543/PM-WWA-20060530-C011.jpg
..    ...                                       ...
995  2352   data-train/2352/PM-WWA-20130829-149.jpg
996  2352   data-train/2352/PM-WWA-20140625-002.jpg
997  2352   data-train/2352/PM-WWA-20140712-198.jpg
998  2352   data-train/2352/PM-WWA-20150823-036.jpg
999  2352   data-train/2352/PM-WWA-20160811-113.jpg

[61 rows x 2 columns]